creating a set of 2 cluster trough kubernetes.Before that we need to have a image already build by dokcer build -t imagename
(here I name it as centos).
*******************************************
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: httpd
   labels:
     tier: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
     tier: webserver
  template:
    metadata:
       labels:
         tier: webserver
    spec:
       containers:
        - name: mywebserver
          image: myweb:latest
