creating a set of 2 cluster trough kubernetes.Before that we need to have a image already build by dokcer build -t imagename
(here I name it as centos).
*******************************************
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver1
  labels:
    tier: webserver1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: webserver1
  template:
    metadata:
      labels:
        tier: webserver1
    spec:
      containers:
        - name: webservice1
          image: centos
